language: objective-c
osx_image: beta-xcode6.3
git:
  depth: 2
branches:
  only:
    - master
    - dev
env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin
node_js:
  - "0.10"
install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config 
  - npm install -g cordova-paramedic
  - npm install -g cordova
  - npm install -g ios-sim
script:
  - cordova-paramedic --platform ios --plugin ${TRAVIS_BUILD_DIR}